### ISSUE TITLE
pdf link broken

### ISSUE THREAD

**Issue by carloswm85** [viacheslav-lozinskyi/MetaOutput#22]
https://viacheslav-lozinskyi.github.io/MetaOutput/resource/document/MetaOutput.pdf

Great tool! Thank you for making it.

I've seen what the project is not open source. What happen if you suddenly die?

And I have another question. I notice what when I write in my code:

![image](https://github.com/viacheslav-lozinskyi/MetaOutput/assets/29048235/811f3e50-9171-4d15-b61e-a9049247fed1)

I get a colored output, as:

![image](https://github.com/viacheslav-lozinskyi/MetaOutput/assets/29048235/347685e0-3227-4348-9749-a54b739d9392)

How do I get different colors? What else can I do with the text style? I was looking for proper markdown (for example) documentation, but found any.

**Comment by viacheslav-lozinskyi** [comment]
Thank you for appreciation of my work.

### About your concerns.

We all will die, its fact.
In my case, I have bigger chances because I live in Ukraine, and almost each day everyone here can be killed.
It's our risk.
It's our fate.
It's our price.

You are right, in this case technology which I made, will by lost.
And restoring it will be difficult, very difficult task...
Moreover, it will be not the biggest loss, because that I plan to do is much more important that was already done.
It will be much more important technologies...

That losses will be much more significant.
Therefore, it's risk and price for whole software industry.

Therefore pray for Ukraine, pray for our victory.


### About your question.

`Debug.WriteLine($"> SAVE CURRENT LOT: {1} @@@FOREGROUND RED");`

It's solution.


### About documentation.

In fact MetaOutput is viewer for TML (Trace Message Language).
Now it's in development, but implemented only draft version of TML.

I don't write documentation by next reasons:
1. I don't encourage discussion about this language until it will be released (it will consume my time).
2. I don't have free resources to do it (I should write documentation instead coding).
3. I don't want to take obligations with compatibility pre-release versions of TML (it will slow down development).

Therefore documentation to TML will be after release of MetaOutput 3.0.
There will be released TML 1.0.
There will be obligation to support it in all next versions of MetaOutput.
That language will be defined as open Internet standard [here](https://www.ietf.org/)


### About broken link.

Thank you for information.
Fix will be released in MetaOutput 3.0.

**Comment by carloswm85** [comment]
Hopefully you'll find a way of let this project (and your other projects) outlive you.

By the way, it would be useful to add a discussion tab to this project. Some topics shouldn't be treated here in the issues sections.

Regards. And take care of yourself in this dangerous times in your country. May God bless you and Ukraines, and we all find peace.

**Comment by viacheslav-lozinskyi** [comment]
Thank you for good wishes.

After end of war I plan to make company which will continue this product.
I will make team, I will make knowledge transfer, I will provide access to source code to that team, I will do everything to make this handover maximally fast and successful.
After that I will do only core of this product, and will do other technologies which in my plans.

It will be more sustainable situation than now.

**P.S.**
I have added discussion tab to GitHub.
It's good idea.
